---
readme: |
  This task generate tags with go version to use in docker image builds
oses:
  - linux
params:
  IMAGE: Name of the image that matches image name in the go_vesion.json file
  GO_MAJOR_MINOR_VERSION:  major.minor version for golang to be used, e.g. 1.24


