---
platform: linux

inputs:
- name: diego-ci

outputs:
- name: envoy-binary

image_resource:
  type: docker-image
  source:
    repository: envoyproxy/envoy
    tag: v1.14-latest

run:
  path: diego-ci/tasks/create_envoy_blob
