---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/diego-pipeline

inputs:
  - name: diego-ci

params:
  CF_USER: ~
  CF_PASSWORD: ~
  CF_TARGET: ~

run:
  path: diego-ci/tasks/enable_diego_docker_feature_flag
