---
platform: linux

inputs:
- name: diego-ci
- name: diego-release
- name: golang-release
outputs:
- name: updated-diego-release

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/diego-pipeline

params:
  secret_access_key: ~
  access_key_id: ~

run:
  path: diego-ci/concourse/update_golang_packages
