---
platform: linux

inputs:
  - name: ci
  - name: repo
  - name: ci-config
    optional: true

outputs:
  - name: synced-repo 

run:
  path: ci/shared/tasks/sync-readme/task.bash

params:
  INTERNAL_REPOS:
