---
platform: linux

inputs:
- name: ci

outputs:
- name: written-file

run:
  path: ci/shared/tasks/write-file/task.bash

params:
  NAME:
  CONTENT:
  INTERPOLATED_VALUE:
  INTERPOLATED_VALUE_2:
  EVAL: false
