---
readme: |
  This task will export jobs for a given release. Release name would be fetched from repo's config/final.yml.
oses:
  - linux
params:
  DIR: (Defaults to .) Change DIR before bosh_target
  BBL_STATE_DIR: name of bbl state dir (relative to the env resource)
  OS:  (defaults to ubuntu). Name of OS.
