---
readme: |
  This task will combine multiple directories into a single directory. This is helpful for collating mulitple directories into a single location for use later.
extra_inputs:
  input-*: Extra inputs that you can match the GLOB with
oses:
  - linux
params:
  GLOB: Glob to match dirs. This will run against all inputs
