---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfdiegodocker/deploy-cf-deployment

inputs:
- name: bosh-stemcell
- name: bosh-windows-stemcell
- name: bosh-windows2016-stemcell
- name: diego-ci
- name: cf-deployment
- name: deployments-diego
- name: diego-release

run:
  path: diego-ci/concourse/deploy_cf_deployment

params:
  DEPLOYMENT_DIR: ~
