---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfdiegodocker/deploy-cf-deployment

inputs:
- name: bosh-stemcell
- name: bosh-windows-stemcell
- name: diego-ci
- name: merged-cf-deployment
- name: deployments-diego
- name: diego-release

run:
  path: diego-ci/concourse/deploy_cf_deployment

params:
  BOSH_ENVIRONMENT: ~
  BOSH_CLIENT: ~
  BOSH_CLIENT_SECRET: ~
  BOSH_DEPLOYMENT: ~
  DEPLOYMENT_DIR: ~
  DEPLOY_WINDOWS_CELL: false
  USE_LOCKET: false
  DEPLOY_ROUTING: false
  USE_LOGGREGATOR_V2: false
  USE_POSTGRES: false
  USE_GROOTFS: false
  USE_BRIDGE_CONSOLIDATION: false
  DETECT_CONSUL_CELL_REGISTRATIONS: true
  DISABLE_CONSUL_SERVICE_REGISTRATION: false
  USE_ETCD: true
  USE_BPM: false
