---
platform: linux

image: docker:///cloudfoundry/diego-pipeline

inputs:
  - name: deployments-runtime
  - name: diego-release
  - name: diego-ci
  - name: cf-release

outputs:
  - name: generated-manifest

params:
  DEPLOYMENTS_DIR: ~
  ENVIRONMENT_NAME: ~
  INFRASTRUCTURE: ~

run:
  path: diego-ci/concourse/generate_deployment_manifests
