---
platform: linux

inputs:
  - name: ci
  - name: repo
  - name: env
  - name: release-01
    optional: true
  - name: release-02
    optional: true
  - name: release-03
    optional: true

params:
  DEPLOYMENT_NAME:
  ENVS:
  MANIFEST:
  OPS_FILES:

run:
  path: ci/shared/tasks/bosh-deploy-manifest/task.bash
