---
platform: linux

inputs:
  - name: ci
  - name: repo
  - name: env
  - name: config
    optional: true
  - name: ops-files
    optional: true
  - name: release-01
    optional: true
  - name: release-02
    optional: true
  - name: release-03
    optional: true

params:
  BBL_STATE_DIR:
  DEPLOYMENT_NAME:
  ENVS:
  EVAL_CMD:
  MANIFEST:
  OPS_FILES:
  VARS_FILES:
  DIR: .

run:
  path: ci/shared/tasks/bosh-deploy-manifest/task.bash
